language: ruby
rvm:
- 2.3.0
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
deploy:
  provider: heroku
  api_key:
    secure: Fe4H09vIwnGc+vOIHYtBU9PMJyJvuT8ONnWD89URj2Om1GU/sJsFOOwwM+p4VIUnHtk3VbF/EDyfVu0flOGPLtyYmbbQRJBC3tRUnQjMtyPPVkKTfj+mdP13wWQg6NM4JLFi2k2zSqdWD18Bw6GDl93nEZrwY6Wkg0BXQMZ2o+sID4DD62e8E5jKBKSjOLM8dQ56uYZf/7V405sC57To7t1rqQBFk1rpJEiFh6XwC3t3u+SvCb4VIESn6DGp0nRniTpJkEj98V9VO3pxi2zhxmCpjmIBf1UmE42P+5cjzcW4WzvOONQqjKYvKhDhJdTTk1oiyovzT6b1I9WpzVZbQ9OWcpq0NuKlaSAhH5HkbNF+eE6TnpTJtAtZeOW9hqU5Q8Dx8JD7/4aH8puwBcgFRfK1J7kZNHU6IamhZavO+Pq/XDa7AtKkhJSdf+zKLark5ozlLzZbEnnwo/Cx5Z9p4RSOGP8a/FO6Wpuek+82SRdF8gHEhKBvuh7h2qjRhFVmk4kgFFxxtXCZuT1vnIYNN0tMMYBTjytMPrfjOj7fzQJg/M+VuyhxNNuPiNwHWGBzXTd+J4CDpCPwWHub6qzRkP/XAjY0eitx03bilOgncnfe0CJYzYvqdeOJx1wfdXG+M3GDDRuq88EeXf50WuF74xJqvXW6i8GE6BikQJOj1Ik=
  app: iron-library
  on:
    repo: bennycazares/iron_library
    run:
      - "rake db:migrate"  
